package main

import (
	"context"
	"fmt"
	"log"

	"github.com/Pavan2027/mcu-rag/retrieval"
	"github.com/Pavan2027/mcu-rag/storage"
)

// A dummy embedder that satisfies the embeddings.Embedder interface
// since test.db currently holds mock embeddings.
type DummyEmbedder struct{}

func (d *DummyEmbedder) EmbedQuery(ctx context.Context, query string) ([]float64, error) {
	// Return a 768-dim slice matching standard dimensions
	return make([]float64, 768), nil
}

func main() {
	fmt.Println("🔍 Initializing Live Retrieval Verification...")

	// 1. Open the real database generated by the parser
	db, err := storage.Open("testdata/test.db", "bin/vec0")
	if err != nil {
		log.Fatalf("❌ Failed to open database: %v", err)
	}
	defer db.Close()

	// 2. Setup embedder and hybrid search options
	embedder := &DummyEmbedder{}
	query := "USART register description"
	opts := retrieval.RetrievalOptions{
		K:          3,
		ChipFamily: "STM32F4", // Apply dynamic SQL filter
	}

	fmt.Printf("\n🔎 Running Hybrid Search + Reranking for query: %q\n", query)
	fmt.Printf("📋 Options: ChipFamily=%s, K=%d\n\n", opts.ChipFamily, opts.K)

	// 3. Execute hybrid search (Vector + FTS RRF merge)
	res, err := retrieval.HybridSearch(context.Background(), db, embedder, query, opts)
	if err != nil {
		log.Fatalf("❌ HybridSearch failed: %v", err)
	}

	if len(res.Chunks) == 0 {
		fmt.Println("⚠️  No chunks retrieved. Make sure testdata/test.db is populated.")
		return
	}

	// 4. Run your Reranker on the hybrid search results
	reranked := retrieval.Rerank(res.Chunks, query, opts.ChipFamily)

	// 5. Print out the retrieved and ranked chunks
	for i, chunk := range reranked {
		fmt.Printf("Rank %d [Chunk ID: %d]\n", i+1, chunk.ChunkID)
		fmt.Printf("  • File:       %s\n", chunk.Filename)
		fmt.Printf("  • Section:    %s\n", chunk.SectionTitle)
		fmt.Printf("  • Peripheral: %s\n", chunk.Peripheral)
		fmt.Printf("  • Register:   %s\n", chunk.RegisterName)
		fmt.Printf("  • Scores:     Semantic=%.4f | FTS=%.4f | Boost=%.4f | FINAL=%.4f\n", 
			chunk.SemanticScore, chunk.FTSScore, chunk.MetadataBoost, chunk.FinalScore)
		fmt.Printf("  • Text Snippet:\n    \"%s...\"\n\n", truncateText(chunk.ChunkText, 150))
	}
}

func truncateText(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen]
}
